services:
  xmlvalidator:
    container_name: xmlvalidator
    image: xmlvalidator:latest
    build: xmlvalidator
    environment:
      PORT: 8080
    ports:
      - 8080:8080

  test:
    container_name: test
    image: musicxml:latest
    build: .
    volumes:
      - './src:/musicxml/src'
    links:
      - xmlvalidator
    ports:
      - 9229:9229
