export const EXAMPLES = {
  ACTOR_PRELUDE_SAMPLE: 'actor_prelude_sample.xml',
  ACTOR_PRELUDE_SAMPLE_PART_NAME: 'actor_prelude_sample_part_name.xml',
  APRES_UN_REVE: 'apres_un_reve.xml',
  CHOPIN_PRELUDE: 'chopin_prelude.xml',
  CONCERT_SCORE_AND_FOR_PART: 'concert_score_and_for_part.xml',
  EXPRESSION_TEST: 'expression_test.xml',
  HELLO_WORLD_MODIFIED: 'hello_world_modified.xml',
  HELLO_WORLD: 'hello_world.xml',
  MOSTLY_INVALID: 'mostly_invalid.xml',
  NOTE_VARIATIONS: 'note_variations.xml',
  PARTIALLY_INVALID: 'partially_invalid.xml',
  SIMPLE_TABLATURE: 'simple_tablature.xml',
  TUTORIAL_PERCUSSION: 'tutorial_percussion.xml',
  TUTOTRIAL_CHORD_SYMBOLS: 'tutorial_chord_symbols.xml',
  WANNA_SKIP_CLASS: 'wanna_skip_class.xml',
} as const;

export const EXAMPLE_SUITES = {
  VALID: [
    EXAMPLES.ACTOR_PRELUDE_SAMPLE,
    EXAMPLES.ACTOR_PRELUDE_SAMPLE_PART_NAME,
    EXAMPLES.APRES_UN_REVE,
    EXAMPLES.CHOPIN_PRELUDE,
    EXAMPLES.CONCERT_SCORE_AND_FOR_PART,
    EXAMPLES.EXPRESSION_TEST,
    EXAMPLES.HELLO_WORLD_MODIFIED,
    EXAMPLES.HELLO_WORLD,
    EXAMPLES.NOTE_VARIATIONS,
    EXAMPLES.SIMPLE_TABLATURE,
    EXAMPLES.TUTORIAL_PERCUSSION,
    EXAMPLES.TUTOTRIAL_CHORD_SYMBOLS,
    EXAMPLES.WANNA_SKIP_CLASS,
  ],
  INVALID: [EXAMPLES.MOSTLY_INVALID, EXAMPLES.PARTIALLY_INVALID],
  GUITAR_PRO: [],
} as const;
