name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        run: yarn test --ci
